apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ashokirlaahsimplegorepo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ashokirlaahsimplegorepo 
    spec:
      containers:
        - name: ashokirlaahsimplegorepo 
          image: ashkiracr.azurecr.io/ashokirlaahsimplegorepo
          ports:
          - containerPort: 80